// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_create_semaphore
Rcpp::String rcpp_create_semaphore(unsigned int value);
RcppExport SEXP _semaphore_rcpp_create_semaphore(SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type value(valueSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_create_semaphore(value));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_increment_semaphore
void rcpp_increment_semaphore(const char* semaphore);
RcppExport SEXP _semaphore_rcpp_increment_semaphore(SEXP semaphoreSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const char* >::type semaphore(semaphoreSEXP);
    rcpp_increment_semaphore(semaphore);
    return R_NilValue;
END_RCPP
}
// rcpp_decrement_semaphore
bool rcpp_decrement_semaphore(const char* semaphore, bool wait);
RcppExport SEXP _semaphore_rcpp_decrement_semaphore(SEXP semaphoreSEXP, SEXP waitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const char* >::type semaphore(semaphoreSEXP);
    Rcpp::traits::input_parameter< bool >::type wait(waitSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_decrement_semaphore(semaphore, wait));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_remove_semaphore
bool rcpp_remove_semaphore(const char* semaphore);
RcppExport SEXP _semaphore_rcpp_remove_semaphore(SEXP semaphoreSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const char* >::type semaphore(semaphoreSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_remove_semaphore(semaphore));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_semaphore_rcpp_create_semaphore", (DL_FUNC) &_semaphore_rcpp_create_semaphore, 1},
    {"_semaphore_rcpp_increment_semaphore", (DL_FUNC) &_semaphore_rcpp_increment_semaphore, 1},
    {"_semaphore_rcpp_decrement_semaphore", (DL_FUNC) &_semaphore_rcpp_decrement_semaphore, 2},
    {"_semaphore_rcpp_remove_semaphore", (DL_FUNC) &_semaphore_rcpp_remove_semaphore, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_semaphore(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
