# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_create_semaphore <- function(value = 0L) {
    .Call(`_semaphore_rcpp_create_semaphore`, value)
}

rcpp_increment_semaphore <- function(semaphore) {
    invisible(.Call(`_semaphore_rcpp_increment_semaphore`, semaphore))
}

rcpp_decrement_semaphore <- function(semaphore, wait = TRUE) {
    .Call(`_semaphore_rcpp_decrement_semaphore`, semaphore, wait)
}

rcpp_remove_semaphore <- function(semaphore) {
    .Call(`_semaphore_rcpp_remove_semaphore`, semaphore)
}

