
#' Shared Memory Atomic Operations
#' 
#' A semaphore is an integer that the operating system keeps track of.
#' Any process that knows the semaphore's identifier can increment or 
#' decrement its value, though it cannot be decremented below zero.\cr\cr
#' When the semaphore is zero, calling `decrement_semaphore(wait = FALSE)` 
#' will return `FALSE` whereas `decrement_semaphore(wait = TRUE)` will 
#' block until the semaphore is incremented by another process. 
#' If multiple processes are blocked, a single call to increment will 
#' only unblock one of the blocked processes.
#' 
#' @param value       The initial value of the semaphore.
#' @param semaphore   A semaphore identifier, as generated by `create_semaphore()`.
#' @param wait        If `TRUE`, blocks until semaphore is greater than zero.
#' 
#' @return
#' * `create_semaphore()` - A semaphore identifier (string).
#' * `increment_semaphore()` - `NULL`, invisibly.
#' * `decrement_semaphore()` - `TRUE` on success; `FALSE` otherwise.
#' * `remove_semaphore()` - `TRUE` on success; `FALSE` on error.
#' 
#' @export
#' @examples
#' 
#'     library(semaphore) 
#'     
#'     s <- create_semaphore()
#'     print(s)
#'     
#'     increment_semaphore(s)
#'     decrement_semaphore(s, wait = FALSE)
#'     decrement_semaphore(s, wait = FALSE)
#'     
#'     remove_semaphore(s)

create_semaphore <- function (value = 0) {
  stopifnot(isTRUE(value >= 0))
  rcpp_create_semaphore(value)
}


#' @rdname create_semaphore
#' @export
increment_semaphore <- function (semaphore) {
  stopifnot(isTRUE(nchar(semaphore) == 20))
  invisible(rcpp_increment_semaphore(semaphore))
}


#' @rdname create_semaphore
#' @export
decrement_semaphore <- function (semaphore, wait = TRUE) {
  stopifnot(isTRUE(nchar(semaphore) == 20))
  stopifnot(isTRUE(wait) || isFALSE(wait))
  res <- rcpp_decrement_semaphore(semaphore, wait)
  if (wait) return (invisible(res)) else return (res)
}


#' @rdname create_semaphore
#' @export
remove_semaphore <- function (semaphore) {
  stopifnot(isTRUE(nchar(semaphore) == 20))
  rcpp_remove_semaphore(semaphore)
}
